# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_x64
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_x64)
  raylib_config = debug_x64
  rlImGui_config = debug_x64
  game_config = debug_x64

else ifeq ($(config),release_x64)
  raylib_config = release_x64
  rlImGui_config = release_x64
  game_config = release_x64

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := raylib rlImGui game

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

raylib:
ifneq (,$(raylib_config))
	@echo "==== Building raylib ($(raylib_config)) ===="
	@${MAKE} --no-print-directory -C _build -f raylib.make config=$(raylib_config)
endif

rlImGui:
ifneq (,$(rlImGui_config))
	@echo "==== Building rlImGui ($(rlImGui_config)) ===="
	@${MAKE} --no-print-directory -C _build -f rlImGui.make config=$(rlImGui_config)
endif

game: raylib rlImGui
ifneq (,$(game_config))
	@echo "==== Building game ($(game_config)) ===="
	@${MAKE} --no-print-directory -C _build -f game.make config=$(game_config)
endif

clean:
	@${MAKE} --no-print-directory -C _build -f raylib.make clean
	@${MAKE} --no-print-directory -C _build -f rlImGui.make clean
	@${MAKE} --no-print-directory -C _build -f game.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_x64"
	@echo "  release_x64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   raylib"
	@echo "   rlImGui"
	@echo "   game"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"